import assert from "node:assert/strict";
import test from "node:test";
import { AppConfig, assertProductionConfigGuards } from "../loadConfig.js";

function makeConfig(): AppConfig {
  return {
    configPath: "./bots.json",
    startupStaggerMs: 0,
    runtimeGuards: {
      allowUserSimulationInProduction: false,
    },
    bots: [],
    sim: {
      enabled: false,
      baseUrl: "http://localhost:3000",
      sessionCookie: "",
      intervalMs: 0,
      orchestratorLoopIntervalMs: 0,
      closeLoopIntervalMs: 0,
      resolveLoopIntervalMs: 0,
      healthLoopIntervalMs: 0,
      failFast: false,
      runSeeder: false,
      runCloser: false,
      runResolver: false,
      runHealthChecker: false,
      targetActiveMarkets: 0,
      maxCreatePerRun: 0,
      maxClosePerRun: 0,
      maxResolvePerRun: 0,
      defaultMarketDurationMinutes: 0,
      resolveDelayMinutes: 0,
      resolverMode: "random_50_50",
      settleAfterResolve: false,
      maxClosedUnresolvedAgeMs: 0,
      emitJsonSummary: false,
    },
  };
}

test("production guard blocks user simulation in production", () => {
  const previous = process.env.NODE_ENV;
  process.env.NODE_ENV = "production";

  try {
    assert.throws(() =>
      assertProductionConfigGuards({
        ...makeConfig(),
        bots: [
          {
            name: "noise",
            baseUrl: "http://localhost:3000",
            apiKey: "pk",
            strategy: "noiseTrader",
            marketIds: ["m1"],
            pollIntervalMs: 1,
            loopIntervalMinMs: 1,
            loopIntervalMaxMs: 1,
            maxOrderSize: "1",
            maxTakerSize: "1",
            maxOpenOrders: 1,
            staleOrderMs: 1,
            minQuoteLifetimeMs: 1,
            decisionCooldownMs: 1,
            capBackoffMs: 1,
            tickSize: "0.01",
            maxPositionShares: "1",
            inventoryTargetShares: "1",
            targetSpreadTicks: 1,
            quoteOffsetMinTicks: 0,
            quoteOffsetMaxTicks: 0,
            staleDistanceTicks: 1,
            replaceThresholdTicks: 1,
            replaceHysteresisTicks: 1,
            maxOrdersPerSide: 1,
            takerProbability: 0,
            takerThresholdTicks: 1,
            inventorySkewStrength: 1,
            fallbackFairPrice: "0.5",
            dailyNotionalPauseMode: "pause_for_run",
            dailyNotionalCooldownMs: 1,
            pausedPollIntervalMs: 1,
            pauseLogIntervalMs: 1,
            referenceAwareSystemLiquidity: {
              referencePollMs: 1,
              referenceStaleMs: 1,
              liquidityBotCycleMs: 1,
              quoteOffsetTicks: 1,
              minReferenceSpread: 0,
              maxReferenceSpread: 1,
              minReferenceLiquidity: null,
              minVolume24hr: null,
              cancelOnReferenceStale: true,
              cancelOnReferenceWide: true,
              dryRun: true,
              explicitBotTradable: false,
            },
            dynamicMarketMaker: {
              minLevelsPerSide: 1,
              maxLevelsPerSide: 1,
              levelSpacingTicks: 1,
              minSpreadTicks: 1,
              maxSpreadTicks: 1,
              baseSpreadTicks: 1,
              extremeSpreadTicks: 1,
              inventorySpreadTicks: 1,
              inventoryLeanTicks: 1,
              inventoryReduceThreshold: 1,
              inventoryEmergencyThreshold: 1,
              levelSizeMultipliers: [1],
              extremeSizeReduction: 0,
              minLevelSize: "1",
              replenishmentTargetShares: "1",
              enableMintReplenishment: false,
              targetAskDepthShares: "1",
              safetyMultiplier: 1,
              targetInventoryShares: "1",
              minMintAmount: "1",
              maxMintAmountPerCycle: "1",
              maxMintPerMarketPerHour: "1",
              extremeMintReductionThresholdHigh: 1,
              extremeMintReductionThresholdLow: 0,
              extremeMintReductionFactor: 0,
              quoteKeepBandTicks: 0,
              quoteKeepSizeToleranceRatio: 0,
              normalMarketTightenTicks: 0,
              selectiveCompetitiveTicks: 0,
              selectiveCompetitiveSizeBumpRatio: 0,
              selectiveCompetitiveMaxInventoryImbalance: 0,
              selectiveCompetitiveMinAvailableUSDC: "0",
              selectiveCompetitiveRecentLagLimit: 0,
              safeCompetitiveJoinTouchBothSides: false,
              safeCompetitiveMinimumObservedSpreadTicks: 0,
            },
            risk: {
              botUserId: null,
              enabled: false,
              maxTotalCapitalCents: 0,
              maxCapitalPerMarketCents: 0,
              maxOpenOrderNotionalCents: 0,
              maxOrderSizeCents: 0,
              maxDailyLossCents: 0,
              maxDailySubmittedNotionalCents: 0,
              maxYesSharesPerMarket: "0",
              maxNoSharesPerMarket: "0",
              maxOrdersPerMarket: 0,
              maxQuoteLevelsPerSide: 0,
              staleDataMaxAgeMs: 0,
              pauseNearResolutionMinutes: 0,
              repeatedErrorPauseMs: 0,
              inventoryReduceOnlyThreshold: 0,
              inventoryStopThreshold: 0,
              emergencyStopOnInvariantViolation: false,
              emergencyStopOnRepeatedApiErrors: false,
              emergencyStopOnBalanceMismatch: false,
              repeatedApiErrorThreshold: 0,
              repeatedApiErrorWindowMs: 0,
              repeatedCancelConflictThreshold: 0,
              repeatedStaleStateThreshold: 0,
              cancelOpenOrdersOnPause: false,
              cancelOpenOrdersOnEmergencyStop: false,
            },
          },
        ],
      }),
    );
    assert.throws(() =>
      assertProductionConfigGuards({
        ...makeConfig(),
        sim: {
          ...makeConfig().sim,
          enabled: true,
        },
      }),
    );
  } finally {
    process.env.NODE_ENV = previous;
  }
});
