import { marketTemplates } from "./marketTemplates.js";
import {
  SIM_MARKET_TAG,
  SIM_MARKET_TITLE_PREFIX,
  SimMarketDraft,
  SimMarketTemplate,
} from "./types.js";

type CreateSimMarketParams = {
  sequence: number;
  now: Date;
  defaultMarketDurationMinutes: number;
  resolveDelayMinutes: number;
};

export function createSimMarketDraft(params: CreateSimMarketParams): SimMarketDraft {
  const template = selectTemplate(params.sequence);
  const variantIndex = Math.floor(params.sequence / marketTemplates.length);
  const variant = template.buildVariant(variantIndex);
  const closeTime = addMinutes(params.now, params.defaultMarketDurationMinutes);
  const resolveTime = addMinutes(closeTime, params.resolveDelayMinutes);
  const suffix = `${params.now.toISOString().slice(0, 16).replace(/[:T]/g, "")}-${params.sequence + 1}`;

  return {
    templateType: template.type,
    closeTime: closeTime.toISOString(),
    resolveTime: resolveTime.toISOString(),
    request: {
      title: `${SIM_MARKET_TITLE_PREFIX} ${variant.title} ${suffix}`,
      description: `${variant.description}\n\nSimulated market generated by poly-bot.\nClose target: ${closeTime.toISOString()}\nResolve target: ${resolveTime.toISOString()}`,
      resolveTime: resolveTime.toISOString(),
      tags: [SIM_MARKET_TAG, "simulated", `template:${template.type}`],
      type: variant.marketType,
      ...(variant.outcomes ? { outcomes: variant.outcomes } : {}),
      visibility: "PUBLIC",
      mechanism: "ORDERBOOK",
      isSimulated: true,
    },
  };
}

function selectTemplate(sequence: number): SimMarketTemplate {
  const template = marketTemplates[sequence % marketTemplates.length];
  if (!template) {
    throw new Error(`No market template available for sequence ${sequence}.`);
  }
  return template;
}

function addMinutes(value: Date, minutes: number): Date {
  return new Date(value.getTime() + minutes * 60_000);
}
